### ISSUE TITLE
TS in testing

### ISSUE THREAD

**Issue by ksnyde** [remojansen/ts-vscode-boilerplate#10]
Thanks for writing your article and providing this repo. One thing I'm trying to understand is the best way of ensuring that `gulp watch` compiles not only my source but also my test files but does it with different config info (like in testing just have the `.ts` compile to the same directory
 for instance whereas in `src` it compiles to `lib`). I also want to ensure the testing pipeline is run when the watcher finds a change in either tests or source code.

This isn't a bug just a question. If you could cover this in your article I bet others would be interested in this.

**Comment by remojansen** [comment]
Sorry for the late reply on this...

So the "watch" task observes changes in app files and test files and executes the default task:

```ts
gulp.watch([ "source/**/**.ts", "test/**/*.ts"], ["default"]);
```

The default task generates a JS file as output so we also observe it and reload the browser:

```ts
 gulp.watch("dist/*.js").on('change', browserSync.reload); 
```

The entire task looks like:

```ts
gulp.task("watch", ["default"], function () {
    
    browserSync.init({
        server: "."
    });
    
    gulp.watch([ "source/**/**.ts", "test/**/*.ts"], ["default"]);
    gulp.watch("dist/*.js").on('change', browserSync.reload); 
});
```

The default task runs the "build" and "test" tasks:
```ts
gulp.task("default", function (cb) {
    runSequence("lint", "build", "test", "bundle", cb);
});
```

And the build task compiles both app code and test code:
```ts
gulp.task("build", function(cb) {
    runSequence(["build-app", "build-test"], cb);
});
```

In summary:

    Change in src / test files ➜ run "default" ➜ changes in JS ➜ reload browser
