### ISSUE TITLE
vs code can not find source mapping for ts files

### ISSUE THREAD

**Issue by avkonst** [remojansen/ts-vscode-boilerplate#2]
Great work and great blog. I have started in minutes.

I have tried to debug as per your guidelines:
$ mocha --debug-brk
vs code attach

1. I can debug generated js code, but VS Code can not set a breakpoint on ts files (can not find source map file)
2. It would be great to improve the template with a gulp task to execute 'mocha --debug-brk' automatically on debugger attach click. I am new to javascript, npm, etc... so it is unlikely I can figure it out quickly. Appreciate your help.
3. It would be great to have some ideas on how to continuously run unit tests (maybe in command line) without wallaby. At the moment I can not afford to buy their license.

Again thanks for the nice template.

**Comment by remojansen** [comment]
Hi @avkonst I will try to work on this when I have a chance but it might take me some time because I'm working a lot on another project. If you know how to do it I would be happy to accept a pull-request. Thanks for the feedback :smile:

**Comment by avkonst** [comment]
Hi, @remojansen  if you give me an idea of what I need to look at and change, I might do something. Otherwise, I have got no idea. Thanks.

**Comment by remojansen** [comment]
I have upgraded this to TS 2.0 added CI and enabled [greenkeper](https://greenkeeper.io/) so the example is always up to date 🚀 

You can use the `gulp watch` task to observe changes and build and run tests automatically.
