### ISSUE TITLE
package.json devDependencies vs dependencies

### ISSUE THREAD

**Issue by niklr** [remojansen/ts-vscode-boilerplate#36]
- What was the reason to put tsify in dependencies instead of devDependencies?
- Is it correct that jQuery is currently included in the minified dist file? Is this intended?

**Comment by remojansen** [comment]
@niklr tsify should be in `devDependencies` it is my mistake that it is in the wrong place. At the end of the build process, your code and all the third party libraries (included Jquery) should end up in one single bundled file.

**Comment by niklr** [comment]
Alright thank you for clarification! I just learned about browserify which is a new concept for me.
