### ISSUE TITLE
ambient renamed to global in latest typings

### ISSUE THREAD

**Issue by Siderite** [remojansen/ts-vscode-boilerplate#5]
> Usages of ambient are now global
> That means in typings.json any ambientDependencies should be renamed globalDependencies and any ambientDevDependencies should be renamed globalDevDependencies.
> It also means --ambient is now --global

(from `https://www.npmjs.com/package/typings`)

**Comment by remojansen** [comment]
Hi I haven't updated this example in some time. Right now I'm on holidays but I will try to update it when I get back. Thanks for reporting the issue!

**Comment by remojansen** [comment]
I have upgraded this to TS 2.0 added CI and enabled [greenkeper](https://greenkeeper.io/) so the example is always up to date 🚀
