### ISSUE TITLE
Crossing of wires, breaking change in tslint

### ISSUE THREAD

**Issue by khamiltonuk** [remojansen/ts-vscode-boilerplate#6]
If a user is following the tutorial [http://blog.wolksoftware.com/setting-up-your-typescript-vs-code-development-environment](http://blog.wolksoftware.com/setting-up-your-typescript-vs-code-development-environment)
they may run into a spot of bother if they use 
`npm install  --save-dev gulp-tslint`
As they will receive the most latest version of tslint greater than version 6 but this repo tslint uses version 4. Since version 4 there has been a breaking change to gulpfile.js and expects the below
`
.pipe(tslint({
    formatter: "verbose"
}))
.pipe(tslint.report())
`
More info [https://github.com/panuhorsmalahti/gulp-tslint/blob/master/CHANGELOG.md](https://github.com/panuhorsmalahti/gulp-tslint/blob/master/CHANGELOG.md)

Perhaps we can view this as a fun obstacle for anyone learning, If we update the package.json we could prevent the problem if some uses npm install from the command line and gulpfile. I suppose the problem could happen again if another module loaded via command line has a breaking change

**Comment by remojansen** [comment]
Hi @khamiltonuk I want to update this to TS 2.0 but right now I have very limited time. If you want to contribute I would be happy to accept a PR

**Comment by khamiltonuk** [comment]
Sweet I've forked and will give it a go!

**Comment by remojansen** [comment]
Thanks a lot for helping out 😄

**Comment by remojansen** [comment]
Hi @jj09 thanks for your PR earlier. I have upgraded this to TS 2.0 added CI and enabled [greenkeper](https://greenkeeper.io/) so the example is always up to date 🚀
